- name: Install Required Packages
  ansible.builtin.apt:
    name: { { item } }
    state: present
  loop: { { casparcg_apt_packages } }

- name: Create necessary directories
  ansible.builtin.include_tasks:
    file: folders.yml

- name: Download CasparCG Server
  ansible.builtin.get_url: 
    url: { { casparcg_download } }
    dest: /tmp/casparcg.zip
    mode: '0775'

- name: Extract Caspar
  ansible.builtin.unarchive:
    src: /tmp/casparcg.zip
    dest: { { casparcg_install_path } }
    remote_src: yes
    owner: { { casparcg_user } }
    group: { { casparcg_user } }

- name: Remove Download
  ansible.builtin.file:
    path: /tmp/casparcg.zip
    state: absent

- name: Create CasparCG Configuration File from Template
  ansible.builtin.include_tasks:
    file: config.yml
    when: replace_casparcg_config is true

- name: Configure CasparCG as a Service
  ansible.builtin.include_tasks:
    file: service.yml
    when: /etc/systemd/system/casparcg.service is absent
